### ISSUE TITLE
[TextModerator] Resource Not Found

### ISSUE THREAD

**Issue by saadzag** [Azure-Samples/cognitive-services-dotnet-sdk-samples#179]
Please use `[API Name] Brief description` as title.

## API Name (Kind)
TextModerator

## Issue Description
I have Azure Subscription and I created the cognitive service, and from a c# console, I'm trying to test the TextModerator project.

When this line is called:
```
var screenResult =
                        client.TextModeration.ScreenText("text/plain", new MemoryStream(Encoding.UTF8.GetBytes(text)), "eng", true, true, null, true);
```
I got the following message:

> Microsoft.CognitiveServices.ContentModerator.Models.APIErrorException : 'Operation returned an invalid status code 'NotFound''

Any Idea?

Saad

**Comment by yangyuan** [comment]
It's very likely wrong endpoint is used.
If you have further questions, feel free to contact Azure support directly.
