### ISSUE TITLE
[Content Moderator] Can not trun off PII using SDK for text moderation

### ISSUE THREAD

**Issue by maple10001** [Azure-Samples/cognitive-services-dotnet-sdk-samples#182]
Please use `[API Name] Brief description` as title.

## API Name (Kind)
`TextModeration `, `ScreenText`

## Issue Description
When using the `ScreenText` from `TextModeration` class sending the request with `PII` flag to `false`, the response still contains the `PII` section in the JSON.
E.g: 
```
var screenResult = client.TextModeration.ScreenText("text/plain", stream, "eng", false, false, null, true);
```

**Comment by yangyuan** [comment]
Please contact Azure support directly.
