### ISSUE TITLE
Ctrl + C in BingSearchv7 SDK samples hangs cmd window

### ISSUE THREAD

**Issue by v-stadam** [Azure-Samples/cognitive-services-dotnet-sdk-samples#51]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>When running either the BingAllSearch solution or any of the standalone ones, the instruction to use Ctrl + C to end things just hangs the command window

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yangyuan** [comment]
This is a legacy ticket which might no longer be valid.
Close this first, feel free to open a new ticket if the issue still exists.
