### ISSUE TITLE
Visual Search SDK sample has exceptions/errors

### ISSUE THREAD

**Issue by v-stadam** [Azure-Samples/cognitive-services-dotnet-sdk-samples#52]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>In both the BingAllSearch solution ("VisualSearch" sample) and the BingVisualSearch solution, choosing an item that submits an image binary returns an error that […]\bin\Debug\netcoreapp2.0\TestImages\image.jpg cannot be found.

Also, in the same two solutions, choosing an item that sends an image URL or image insights token fails with an “Operation returned an invalid status code 'Unauthorized'” exception even though I'm using a BingSearchv7 app key.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yangyuan** [comment]
This is a legacy ticket which might no longer be valid.
Close this first, feel free to open a new ticket if the issue still exists.
