### ISSUE TITLE
Docker support, container doesn't want to  start

### ISSUE THREAD

**Issue by Morhpeuss** [Azure-Samples/cognitive-services-dotnet-sdk-samples#96]
Hi,

I trained a model in Custom vision. I exported this model to support Docker. I build an image a start a container.

But the container exited. After I attach to the container I see this error:

File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 541, in import_graph_def
raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named LeakyRelu in defined operations.

This looks like Tensorflow exception, but I am not able to resolve it.

**Comment by shonohs** [comment]
Hi,

The cause of this issue is that the docker image is using an old version of tensorflow. Please update the version number of tensorflow in requirements.txt. We recommend 1.13.1.

**Comment by Morhpeuss** [comment]
Thanks, that solved my problem
